### ISSUE TITLE
ES6 default props

### ISSUE THREAD

**Issue by hamedmam** [telus/telus-standard#58]
Telus Standard takes a rule from AirBnB that enforces defaultProps for every non-required prop; but defaultProps are being deprecated for functional components e.g. https://github.com/facebook/react/pull/16210 .
There's a flag we could use for that linting rule, ignoreFunctionalComponents  (default is false).
As well as being deprecated, defaultProps are a bit of a pain especially when you want the default prop to be undefined (I was just writing a utility function to default all a FC's default props to undefined which is what prompted me to write this)
we recommend adding that flag to our linting and start using ES6 prop defaults as recommended? (i.e. like ```const Something = ({ variant = 'default' }) => {...```
we suggest that Telus Standard add that flag.
Default props will still be required for any class components (where they make sense and are more useful)

**Comment by hamedmam** [comment]
suggestion coming from our consultant @AlanSl

**Comment by Nitin-TELUS** [comment]
Thanks @hamedmam for the suggestion. We'll take a look and incorporate this change ASAP.

**Comment by saydex** [comment]
Thanks @Nitin-TELUS! Please let us know if you need any help as well.

**Comment by afzal-telus** [comment]
Hello @hamedmam we've added a rule for the same, Please have a look. [PR#59](https://github.com/telus/telus-standard/pull/59)

Thanks.

**Comment by Nitin-TELUS** [comment]
Hi @hamedmam, closing this issue as it's resolved with the latest release v3.0.1.
